### ISSUE TITLE
Podfile dependency issue

### ISSUE THREAD

**Issue by fawkeswei** [AFNetworking/AFHTTPRequestOperationLogger#16]
`AFHTTPRequestOperationLogger` is requiring `AFNetworking (>= 0.9.0)`

which causes this error 

[!] The platform of the target `Pods` (iOS 5.0) is not compatible with `AFNetworking (2.0.0-RC1)` which has a minimum requirement of iOS 7.0 - OS X 10.9.

**Comment by vburojevic** [comment]
Started happening to me too

**Comment by mattt** [comment]
This is now fixed with the 1.0 release.
