### ISSUE TITLE
Update the podspec

### ISSUE THREAD

**Issue by kcharwood** [AFNetworking/AFHTTPRequestOperationLogger#19]
Can we update the podspec to support AF 2.0.0? It should still work just fine for the NSURLConnection APIs, but cocoapods is currently preventing the install because it says it requires 1.x

We need to add support for NSURLSession, but thats a larger discussion on how to best add that from a modular perspective.

**Comment by mattt** [comment]
AFHTTPRequestOperationLogger is deprecated with AFNetworking 2.0. From now on, please use [AFNetworkActivityLogger](https://github.com/AFNetworking/AFNetworkActivityLogger).
