### ISSUE TITLE
AFNetworking 2.0

### ISSUE THREAD

**Issue by pajapro** [AFNetworking/AFHTTPRequestOperationLogger#20]
When will the AFHTTPRequestOperationLogger work in AFNetworking 2.0?

**Comment by Hackmodford** [comment]
Yeah it doesn't work with 2.0 :(

**Comment by priteshshah1983** [comment]
You can try this PR: https://github.com/AFNetworking/AFHTTPRequestOperationLogger/pull/21

It works for me with 2.0.

**Comment by pajapro** [comment]
@priteshshah1983 how can I get your changes? I can only see that you intent to commit your changes to the Master branch, but cannot clone it to my desktop (sorry newbie to GIT) 
![screen shot 2013-10-17 at 11 01 44 pm](https://f.cloud.github.com/assets/3673765/1355987/cda60596-376f-11e3-8726-eb03f4900c70.png)

**Comment by priteshshah1983** [comment]
One possible way is to add a file called AFHTTPRequestOperationLogger.podspec on your desktop with the following contents:

```
Pod::Spec.new do |s|
  s.name     = 'AFHTTPRequestOperationLogger'
  s.version  = '1.0.0'
  s.license  = 'MIT'
  s.summary  = 'AFNetworking Extension for HTTP Request Logging'
  s.homepage = 'https://github.com/AFNetworking/AFHTTPRequestOperationLogger'
  s.authors  = { 'Mattt Thompson' => 'm@mattt.me' }
  s.source   = { :git => 'https://github.com/AFNetworking/AFHTTPRequestOperationLogger.git'}
  s.source_files = 'AFHTTPRequestOperationLogger.{h,m}'
  s.requires_arc = true

  s.dependency 'AFNetworking', '~> 2.0.0'
  s.ios.deployment_target = '6.0'
end
```

and then add this line to your Podfile:

```
pod 'AFHTTPRequestOperationLogger', :podspec => 'AFHTTPRequestOperationLogger.podspec'
```

Later when this issue is resolved, you can just take out the :podspec part from the Podfile.

**Comment by pajapro** [comment]
Thanks a lot @priteshshah1983 now AFHTTPRequestOperationLogger is installed in my project. 

However, I set the [[AFHTTPRequestOperationLogger sharedLogger] startLogging]; in my AppDelegate and when I call a AFHTTPSessionManager GET request - yet it does not log anything to the console. Any clue why?

I thought that s.ios.deployment_target = '6.0' in AFHTTPRequestOperationLogger.podspec could cause problem since I target iOS 7.0 in my project, but changing it to 7.0 does not make it work.

Appreciate

**Comment by mattt** [comment]
AFHTTPRequestOperationLogger is deprecated with AFNetworking 2.0. Please use [AFNetworkActivityLogger](https://github.com/AFNetworking/AFNetworkActivityLogger) from now on. I've added a note on the README to clarify this.

**Comment by priteshshah1983** [comment]
Thanks @mattt!
