### ISSUE TITLE
-[NSMutableURLRequest allHeaderFields]: unrecognized

### ISSUE THREAD

**Issue by krzyzanowskim** [AFNetworking/AFHTTPRequestOperationLogger#4]
-[NSMutableURLRequest allHeaderFields]: unrecognized selector sent to instance 0x88cbcb0

is there allHeaderFields on NSURLRequest ?

**Comment by mattt** [comment]
Oh the perils of find-and-replace. Either way, I'm rather surprised that Apple would allow for this kind of inconsistency in their APIs. Anyway, fixed in d2cecb1. Thanks.
